#!/bin/bash

TARGET_DIR=pack

rm -rf $TARGET_DIR

src_c=`find . -name "*.c"`
src_h=`find . -name "*.h"`
src_mk=`find . \( -name Makefile -o -name "*.mak" \)`

# Process each source code in .c and .h.
for src in $src_c $src_h; do
	dir="$TARGET_DIR/`dirname $src`"
	src_name="`basename $src`"
	if [ ! -d $dir ]; then
		mkdir -p $dir
	fi
	# Remove comment using preprocessor.
	# And use indent to make the result comfort to Linux coding style
	cat script/license.txt > "$dir/$src_name"
	gcc -fpreprocessed -dD -E -P $src |
	indent -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 \
	-cli0 -d0 -di1 -nfc1 -i8 -ip0 -l80 -lp -npcs -nprs -npsl -sai \
	-saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1 >> "$dir/$src_name"
	#$src | script/stripcmt > "$dir/$src_name"
done

# Copy every Makefile
for src in $src_mk; do
	cp $src "$TARGET_DIR/$src"
done

# No firmware code
rm -rf "$TARGET_DIR/ssv6200smac/firmware"

# Copy scripts and FW image
cp -r image script *.sh $TARGET_DIR
